// <auto-generated />
using System;
using AstrhoApp.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AstrhoApp.API.Migrations
{
    [DbContext(typeof(AstrhoAppDbContext))]
    [Migration("20260320051823_observacioncompra")]
    partial class observacioncompra
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AstrhoApp.API.Models.Agendum", b =>
                {
                    b.Property<int>("AgendaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("agenda_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AgendaId"));

                    b.Property<string>("DocumentoCliente")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("documento_cliente");

                    b.Property<string>("DocumentoEmpleado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("documento_empleado");

                    b.Property<int?>("EstadoId")
                        .HasColumnType("int")
                        .HasColumnName("estado_id");

                    b.Property<DateOnly>("FechaCita")
                        .HasColumnType("date")
                        .HasColumnName("fecha_cita");

                    b.Property<TimeOnly>("HoraInicio")
                        .HasColumnType("time")
                        .HasColumnName("hora_inicio");

                    b.Property<int>("MetodopagoId")
                        .HasColumnType("int")
                        .HasColumnName("metodopago_Id");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(150)
                        .IsUnicode(false)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("observaciones");

                    b.Property<string>("VentaId")
                        .HasMaxLength(25)
                        .IsUnicode(false)
                        .HasColumnType("varchar(25)")
                        .HasColumnName("venta_id");

                    b.HasKey("AgendaId")
                        .HasName("PK__Agenda__461B3C85E20AC940");

                    b.HasIndex("DocumentoCliente");

                    b.HasIndex("DocumentoEmpleado");

                    b.HasIndex("EstadoId");

                    b.HasIndex("MetodopagoId");

                    b.HasIndex("VentaId");

                    b.ToTable("Agenda", t =>
                        {
                            t.HasTrigger("TR_Agenda_VentaId_Unique");
                        });

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);
                });

            modelBuilder.Entity("AstrhoApp.API.Models.Categorium", b =>
                {
                    b.Property<int>("CategoriaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("categoria_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoriaId"));

                    b.Property<string>("Descripcion")
                        .HasMaxLength(150)
                        .IsUnicode(false)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("descripcion");

                    b.Property<bool>("Estado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("estado");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(40)
                        .IsUnicode(false)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("nombre");

                    b.HasKey("CategoriaId")
                        .HasName("PK__Categori__DB875A4FA0E0C35B");

                    b.ToTable("Categoria");
                });

            modelBuilder.Entity("AstrhoApp.API.Models.Cliente", b =>
                {
                    b.Property<string>("DocumentoCliente")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("documento_cliente");

                    b.Property<string>("Dirección")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<bool>("Estado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("estado");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("nombre");

                    b.Property<string>("Telefono")
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)")
                        .HasColumnName("telefono");

                    b.Property<string>("TipoDocumento")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("tipo_documento");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int")
                        .HasColumnName("usuario_id");

                    b.HasKey("DocumentoCliente")
                        .HasName("PK_Documento_Cliente");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Cliente", (string)null);
                });

            modelBuilder.Entity("AstrhoApp.API.Models.Compra", b =>
                {
                    b.Property<int>("CompraId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("compra_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CompraId"));

                    b.Property<bool?>("Estado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("estado");

                    b.Property<DateTime?>("FechaRegistro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("fecha_registro")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<decimal?>("Iva")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(5, 2)")
                        .HasDefaultValue(19m)
                        .HasColumnName("iva");

                    b.Property<string>("Observacion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProveedorId")
                        .HasColumnType("int")
                        .HasColumnName("proveedor_id");

                    b.Property<decimal>("Subtotal")
                        .HasColumnType("decimal(12, 2)")
                        .HasColumnName("subtotal");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(12, 2)")
                        .HasColumnName("total");

                    b.HasKey("CompraId")
                        .HasName("PK__Compra__7B94793C8EE98F55");

                    b.HasIndex("ProveedorId");

                    b.ToTable("Compra", (string)null);
                });

            modelBuilder.Entity("AstrhoApp.API.Models.DetalleCompra", b =>
                {
                    b.Property<int>("DetalleCompraId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("detalleCompra_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DetalleCompraId"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("int")
                        .HasColumnName("cantidad");

                    b.Property<int>("CompraId")
                        .HasColumnType("int")
                        .HasColumnName("compra_id");

                    b.Property<int>("InsumoId")
                        .HasColumnType("int")
                        .HasColumnName("insumo_id");

                    b.Property<decimal>("PrecioUnitario")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("precio_unitario");

                    b.HasKey("DetalleCompraId")
                        .HasName("PK__DetalleC__E25F22054AD39B08");

                    b.HasIndex("CompraId");

                    b.HasIndex("InsumoId");

                    b.ToTable("DetalleCompra", (string)null);
                });

            modelBuilder.Entity("AstrhoApp.API.Models.DetalleEntrega", b =>
                {
                    b.Property<int>("DetalleEntregaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("detalleEntrega_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DetalleEntregaId"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("int")
                        .HasColumnName("cantidad");

                    b.Property<int>("EntregainsumoId")
                        .HasColumnType("int")
                        .HasColumnName("entregainsumo_id");

                    b.Property<int>("InsumoId")
                        .HasColumnType("int")
                        .HasColumnName("insumo_id");

                    b.HasKey("DetalleEntregaId")
                        .HasName("PK__DetalleP__482B835C47786F7D");

                    b.HasIndex("EntregainsumoId");

                    b.HasIndex("InsumoId");

                    b.ToTable("DetalleEntrega", (string)null);
                });

            modelBuilder.Entity("AstrhoApp.API.Models.DetalleVenta", b =>
                {
                    b.Property<int>("DetalleVentaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("detalleVenta_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DetalleVentaId"));

                    b.Property<decimal>("Precio")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("precio");

                    b.Property<int>("ServicioId")
                        .HasColumnType("int")
                        .HasColumnName("servicio_id");

                    b.Property<string>("VentaId")
                        .IsRequired()
                        .HasMaxLength(25)
                        .IsUnicode(false)
                        .HasColumnType("varchar(25)")
                        .HasColumnName("venta_id");

                    b.HasKey("DetalleVentaId")
                        .HasName("PK_DetalleVenta");

                    b.HasIndex("ServicioId");

                    b.HasIndex("VentaId");

                    b.ToTable("DetalleVenta", (string)null);
                });

            modelBuilder.Entity("AstrhoApp.API.Models.Empleado", b =>
                {
                    b.Property<string>("DocumentoEmpleado")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("documento_empleado");

                    b.Property<string>("Dirección")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<bool>("Estado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("estado");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(60)
                        .IsUnicode(false)
                        .HasColumnType("varchar(60)")
                        .HasColumnName("nombre");

                    b.Property<string>("Telefono")
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)")
                        .HasColumnName("telefono");

                    b.Property<string>("TipoDocumento")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("tipo_documento");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int")
                        .HasColumnName("usuario_id");

                    b.HasKey("DocumentoEmpleado")
                        .HasName("PK_Documento_Empleado");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Empleado", (string)null);
                });

            modelBuilder.Entity("AstrhoApp.API.Models.Entregainsumo", b =>
                {
                    b.Property<int>("EntregainsumoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("entregainsumo_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EntregainsumoId"));

                    b.Property<string>("DocumentoEmpleado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("documento_empleado");

                    b.Property<bool?>("Estado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("estado");

                    b.Property<DateTime?>("FechaCompletado")
                        .HasColumnType("datetime")
                        .HasColumnName("fecha_completado");

                    b.Property<DateTime?>("FechaCreado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("fecha_creado")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<DateTime>("FechaEntrega")
                        .HasColumnType("datetime")
                        .HasColumnName("fecha_entrega");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int")
                        .HasColumnName("usuario_id");

                    b.HasKey("EntregainsumoId")
                        .HasName("PK__Entregai__A68F46B19994B5E2");

                    b.HasIndex("DocumentoEmpleado");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Entregainsumo", (string)null);
                });

            modelBuilder.Entity("AstrhoApp.API.Models.Estado", b =>
                {
                    b.Property<int>("EstadoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("estado_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EstadoId"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("nombre");

                    b.HasKey("EstadoId")
                        .HasName("PK__Estado__053774EFAEF9DE03");

                    b.ToTable("Estado", (string)null);
                });

            modelBuilder.Entity("AstrhoApp.API.Models.Horario", b =>
                {
                    b.Property<int>("HorarioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("horario_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("HorarioId"));

                    b.Property<string>("DiaSemana")
                        .IsRequired()
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)")
                        .HasColumnName("dia_semana");

                    b.Property<bool>("Estado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("estado");

                    b.Property<TimeOnly>("HoraFin")
                        .HasColumnType("time")
                        .HasColumnName("hora_fin");

                    b.Property<TimeOnly>("HoraInicio")
                        .HasColumnType("time")
                        .HasColumnName("hora_inicio");

                    b.HasKey("HorarioId")
                        .HasName("PK__Horario__5A3872284E751019");

                    b.ToTable("Horario", (string)null);
                });

            modelBuilder.Entity("AstrhoApp.API.Models.HorarioEmpleado", b =>
                {
                    b.Property<int>("HorarioEmpleadoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("horarioEmpleado_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("HorarioEmpleadoId"));

                    b.Property<string>("DocumentoEmpleado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("documento_empleado");

                    b.Property<int>("HorarioId")
                        .HasColumnType("int")
                        .HasColumnName("horario_id");

                    b.HasKey("HorarioEmpleadoId")
                        .HasName("PK__HorarioE__2DCE8B136FB204D3");

                    b.HasIndex("DocumentoEmpleado");

                    b.HasIndex("HorarioId");

                    b.ToTable("HorarioEmpleado", (string)null);
                });

            modelBuilder.Entity("AstrhoApp.API.Models.Insumo", b =>
                {
                    b.Property<int>("InsumoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("insumo_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("InsumoId"));

                    b.Property<int>("CategoriaId")
                        .HasColumnType("int")
                        .HasColumnName("categoria_id");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("descripcion");

                    b.Property<bool?>("Estado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("estado");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(80)
                        .IsUnicode(false)
                        .HasColumnType("varchar(80)")
                        .HasColumnName("nombre");

                    b.Property<string>("Sku")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("SKU");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.HasKey("InsumoId")
                        .HasName("PK_Insumo_id");

                    b.HasIndex("CategoriaId");

                    b.HasIndex(new[] { "Sku" }, "UQ_SKU")
                        .IsUnique();

                    b.ToTable("Insumo", (string)null);
                });

            modelBuilder.Entity("AstrhoApp.API.Models.Marca", b =>
                {
                    b.Property<int>("MarcaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("marca_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MarcaId"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(80)
                        .IsUnicode(false)
                        .HasColumnType("varchar(80)")
                        .HasColumnName("nombre");

                    b.HasKey("MarcaId")
                        .HasName("PK__Marca__BBC43191A04C5D79");

                    b.ToTable("Marca", (string)null);
                });

            modelBuilder.Entity("AstrhoApp.API.Models.MetodoPago", b =>
                {
                    b.Property<int>("MetodopagoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("metodopago_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MetodopagoId"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("nombre");

                    b.HasKey("MetodopagoId")
                        .HasName("PK__MetodoPa__EEA4EA958277E2F2");

                    b.ToTable("MetodoPago", (string)null);
                });

            modelBuilder.Entity("AstrhoApp.API.Models.Permiso", b =>
                {
                    b.Property<int>("PermisoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("permiso_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PermisoId"));

                    b.Property<string>("Descripcion")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("descripcion");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("nombre");

                    b.HasKey("PermisoId")
                        .HasName("PK__Permiso__60B569CD7DF25DF4");

                    b.ToTable("Permiso", (string)null);
                });

            modelBuilder.Entity("AstrhoApp.API.Models.Proveedor", b =>
                {
                    b.Property<int>("ProveedorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("proveedor_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProveedorId"));

                    b.Property<string>("Ciudad")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("ciudad");

                    b.Property<string>("Correo")
                        .HasMaxLength(80)
                        .IsUnicode(false)
                        .HasColumnType("varchar(80)")
                        .HasColumnName("correo");

                    b.Property<string>("Departamento")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("departamento");

                    b.Property<string>("Direccion")
                        .HasMaxLength(150)
                        .IsUnicode(false)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("direccion");

                    b.Property<string>("Documento")
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)");

                    b.Property<bool?>("Estado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("estado");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(80)
                        .IsUnicode(false)
                        .HasColumnType("varchar(80)")
                        .HasColumnName("nombre");

                    b.Property<string>("PersonaContacto")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("persona_contacto");

                    b.Property<string>("Telefono")
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)")
                        .HasColumnName("telefono");

                    b.Property<string>("TipoDocumento")
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)");

                    b.Property<string>("TipoProveedor")
                        .IsRequired()
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)")
                        .HasColumnName("tipo_proveedor");

                    b.HasKey("ProveedorId")
                        .HasName("PK__Proveedo__88BBADA4F1BDA68B");

                    b.HasIndex(new[] { "Documento" }, "UQ__Proveedo__AF73706D58875709")
                        .IsUnique()
                        .HasFilter("[Documento] IS NOT NULL");

                    b.ToTable("Proveedor", (string)null);
                });

            modelBuilder.Entity("AstrhoApp.API.Models.Rol", b =>
                {
                    b.Property<int>("RolId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("rol_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RolId"));

                    b.Property<string>("Descripcion")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("descripcion");

                    b.Property<bool>("Estado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("estado");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("nombre");

                    b.HasKey("RolId")
                        .HasName("PK__Rol__CF32E443170986B9");

                    b.ToTable("Rol", (string)null);
                });

            modelBuilder.Entity("AstrhoApp.API.Models.RolPermiso", b =>
                {
                    b.Property<int>("RolPermisoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("rolPermiso_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RolPermisoId"));

                    b.Property<int>("PermisoId")
                        .HasColumnType("int")
                        .HasColumnName("permiso_id");

                    b.Property<int>("RolId")
                        .HasColumnType("int")
                        .HasColumnName("rol_id");

                    b.HasKey("RolPermisoId")
                        .HasName("PK__RolPermi__8632A68FED542866");

                    b.HasIndex("PermisoId");

                    b.HasIndex("RolId");

                    b.ToTable("RolPermiso", (string)null);
                });

            modelBuilder.Entity("AstrhoApp.API.Models.Servicio", b =>
                {
                    b.Property<int>("ServicioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("servicio_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ServicioId"));

                    b.Property<string>("Descripcion")
                        .HasMaxLength(150)
                        .IsUnicode(false)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("descripcion");

                    b.Property<int>("Duracion")
                        .HasColumnType("int")
                        .HasColumnName("duracion");

                    b.Property<bool>("Estado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("estado");

                    b.Property<string>("Imagen")
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("imagen");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(60)
                        .IsUnicode(false)
                        .HasColumnType("varchar(60)")
                        .HasColumnName("nombre");

                    b.Property<decimal>("Precio")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("precio");

                    b.HasKey("ServicioId")
                        .HasName("PK__Servicio__AF3A090C218DE604");

                    b.ToTable("Servicio", (string)null);
                });

            modelBuilder.Entity("AstrhoApp.API.Models.ServicioAgendum", b =>
                {
                    b.Property<int>("ServicioAgendaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("servicioAgenda_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ServicioAgendaId"));

                    b.Property<int>("AgendaId")
                        .HasColumnType("int")
                        .HasColumnName("agenda_id");

                    b.Property<int>("ServicioId")
                        .HasColumnType("int")
                        .HasColumnName("servicio_id");

                    b.HasKey("ServicioAgendaId")
                        .HasName("PK__Servicio__B789B9B3CF75B2B6");

                    b.HasIndex("AgendaId");

                    b.HasIndex("ServicioId");

                    b.ToTable("ServicioAgenda");
                });

            modelBuilder.Entity("AstrhoApp.API.Models.Usuario", b =>
                {
                    b.Property<int>("UsuarioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("usuario_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UsuarioId"));

                    b.Property<string>("Contrasena")
                        .IsRequired()
                        .HasMaxLength(64)
                        .IsUnicode(false)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("contrasena");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("email");

                    b.Property<bool>("Estado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("estado");

                    b.Property<bool>("MustChangePassword")
                        .HasColumnType("bit");

                    b.Property<int>("RolId")
                        .HasColumnType("int")
                        .HasColumnName("rol_id");

                    b.HasKey("UsuarioId")
                        .HasName("PK__Usuario__2ED7D2AFAC0B2A1E");

                    b.HasIndex("RolId");

                    b.ToTable("Usuario", (string)null);
                });

            modelBuilder.Entity("AstrhoApp.API.Models.Ventum", b =>
                {
                    b.Property<string>("VentaId")
                        .HasMaxLength(25)
                        .IsUnicode(false)
                        .HasColumnType("varchar(25)")
                        .HasColumnName("venta_id");

                    b.Property<string>("DocumentoCliente")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("documento_cliente");

                    b.Property<string>("DocumentoEmpleado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Estado")
                        .HasColumnType("bit")
                        .HasColumnName("estado");

                    b.Property<DateTime?>("FechaRegistro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("fecha_registro")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("MetodopagoId")
                        .HasColumnType("int")
                        .HasColumnName("metodopago_id");

                    b.Property<decimal>("Subtotal")
                        .HasColumnType("decimal(12, 2)")
                        .HasColumnName("subtotal");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(12, 2)")
                        .HasColumnName("total");

                    b.Property<string>("observacion")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("VentaId")
                        .HasName("PK__Venta__B1350809C97AAD0F");

                    b.HasIndex("DocumentoCliente");

                    b.HasIndex("MetodopagoId");

                    b.ToTable("Venta");
                });

            modelBuilder.Entity("AstrhoApp.API.Models.Agendum", b =>
                {
                    b.HasOne("AstrhoApp.API.Models.Cliente", "DocumentoClienteNavigation")
                        .WithMany("Agenda")
                        .HasForeignKey("DocumentoCliente")
                        .IsRequired()
                        .HasConstraintName("FK_Agenda_Documento_Cliente");

                    b.HasOne("AstrhoApp.API.Models.Empleado", "DocumentoEmpleadoNavigation")
                        .WithMany("Agenda")
                        .HasForeignKey("DocumentoEmpleado")
                        .IsRequired()
                        .HasConstraintName("FK_Agenda_Documento_Empleado");

                    b.HasOne("AstrhoApp.API.Models.Estado", "Estado")
                        .WithMany("Agenda")
                        .HasForeignKey("EstadoId")
                        .HasConstraintName("FK_Agenda_estado_id");

                    b.HasOne("AstrhoApp.API.Models.MetodoPago", "Metodopago")
                        .WithMany("Agenda")
                        .HasForeignKey("MetodopagoId")
                        .IsRequired()
                        .HasConstraintName("FK_Agenda_metodopago_id");

                    b.HasOne("AstrhoApp.API.Models.Ventum", "Venta")
                        .WithMany("Agenda")
                        .HasForeignKey("VentaId")
                        .HasConstraintName("FK_Agenda_Venta");

                    b.Navigation("DocumentoClienteNavigation");

                    b.Navigation("DocumentoEmpleadoNavigation");

                    b.Navigation("Estado");

                    b.Navigation("Metodopago");

                    b.Navigation("Venta");
                });

            modelBuilder.Entity("AstrhoApp.API.Models.Cliente", b =>
                {
                    b.HasOne("AstrhoApp.API.Models.Usuario", "Usuario")
                        .WithMany("Clientes")
                        .HasForeignKey("UsuarioId")
                        .IsRequired()
                        .HasConstraintName("FK__Cliente__usuario__6C190EBB");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("AstrhoApp.API.Models.Compra", b =>
                {
                    b.HasOne("AstrhoApp.API.Models.Proveedor", "Proveedor")
                        .WithMany("Compras")
                        .HasForeignKey("ProveedorId")
                        .IsRequired()
                        .HasConstraintName("FK__Compra__proveedo__6383C8BA");

                    b.Navigation("Proveedor");
                });

            modelBuilder.Entity("AstrhoApp.API.Models.DetalleCompra", b =>
                {
                    b.HasOne("AstrhoApp.API.Models.Compra", "Compra")
                        .WithMany("DetalleCompras")
                        .HasForeignKey("CompraId")
                        .IsRequired()
                        .HasConstraintName("FK__DetalleCo__compr__66603565");

                    b.HasOne("AstrhoApp.API.Models.Insumo", "Insumo")
                        .WithMany("DetalleCompras")
                        .HasForeignKey("InsumoId")
                        .IsRequired()
                        .HasConstraintName("FK_DetalleCo_Insumo");

                    b.Navigation("Compra");

                    b.Navigation("Insumo");
                });

            modelBuilder.Entity("AstrhoApp.API.Models.DetalleEntrega", b =>
                {
                    b.HasOne("AstrhoApp.API.Models.Entregainsumo", "Entregainsumo")
                        .WithMany("DetalleEntregas")
                        .HasForeignKey("EntregainsumoId")
                        .IsRequired()
                        .HasConstraintName("FK__DetallePr__entre__123EB7A3");

                    b.HasOne("AstrhoApp.API.Models.Insumo", "Insumo")
                        .WithMany("DetalleEntregas")
                        .HasForeignKey("InsumoId")
                        .IsRequired()
                        .HasConstraintName("FK_DetalleEn_Insumo");

                    b.Navigation("Entregainsumo");

                    b.Navigation("Insumo");
                });

            modelBuilder.Entity("AstrhoApp.API.Models.DetalleVenta", b =>
                {
                    b.HasOne("AstrhoApp.API.Models.Servicio", "Servicio")
                        .WithMany("DetalleVentas")
                        .HasForeignKey("ServicioId")
                        .IsRequired()
                        .HasConstraintName("FK_DetalleVenta_Servicio");

                    b.HasOne("AstrhoApp.API.Models.Ventum", "Venta")
                        .WithMany("DetalleVentas")
                        .HasForeignKey("VentaId")
                        .IsRequired()
                        .HasConstraintName("FK_DetalleVenta_Venta");

                    b.Navigation("Servicio");

                    b.Navigation("Venta");
                });

            modelBuilder.Entity("AstrhoApp.API.Models.Empleado", b =>
                {
                    b.HasOne("AstrhoApp.API.Models.Usuario", "Usuario")
                        .WithMany("Empleados")
                        .HasForeignKey("UsuarioId")
                        .IsRequired()
                        .HasConstraintName("FK__Empleado__usuari__7D439ABD");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("AstrhoApp.API.Models.Entregainsumo", b =>
                {
                    b.HasOne("AstrhoApp.API.Models.Empleado", "DocumentoEmpleadoNavigation")
                        .WithMany("Entregainsumos")
                        .HasForeignKey("DocumentoEmpleado")
                        .IsRequired()
                        .HasConstraintName("FK_EntregaIn_Documento_Empleado");

                    b.HasOne("AstrhoApp.API.Models.Usuario", "Usuario")
                        .WithMany("Entregainsumos")
                        .HasForeignKey("UsuarioId")
                        .IsRequired()
                        .HasConstraintName("FK__Entregain__usuar__0F624AF8");

                    b.Navigation("DocumentoEmpleadoNavigation");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("AstrhoApp.API.Models.HorarioEmpleado", b =>
                {
                    b.HasOne("AstrhoApp.API.Models.Empleado", "DocumentoEmpleadoNavigation")
                        .WithMany("HorarioEmpleados")
                        .HasForeignKey("DocumentoEmpleado")
                        .IsRequired()
                        .HasConstraintName("FK_HorarioEmp_Documento_Empleado");

                    b.HasOne("AstrhoApp.API.Models.Horario", "Horario")
                        .WithMany("HorarioEmpleados")
                        .HasForeignKey("HorarioId")
                        .IsRequired()
                        .HasConstraintName("FK__HorarioEm__horar__04E4BC85");

                    b.Navigation("DocumentoEmpleadoNavigation");

                    b.Navigation("Horario");
                });

            modelBuilder.Entity("AstrhoApp.API.Models.Insumo", b =>
                {
                    b.HasOne("AstrhoApp.API.Models.Categorium", "Categoria")
                        .WithMany("Insumos")
                        .HasForeignKey("CategoriaId")
                        .IsRequired()
                        .HasConstraintName("FK__Producto__catego__5165187F");

                    b.Navigation("Categoria");
                });

            modelBuilder.Entity("AstrhoApp.API.Models.RolPermiso", b =>
                {
                    b.HasOne("AstrhoApp.API.Models.Permiso", "Permiso")
                        .WithMany("RolPermisos")
                        .HasForeignKey("PermisoId")
                        .IsRequired()
                        .HasConstraintName("FK__RolPermis__permi__3F466844");

                    b.HasOne("AstrhoApp.API.Models.Rol", "Rol")
                        .WithMany("RolPermisos")
                        .HasForeignKey("RolId")
                        .IsRequired()
                        .HasConstraintName("FK__RolPermis__rol_i__3E52440B");

                    b.Navigation("Permiso");

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("AstrhoApp.API.Models.ServicioAgendum", b =>
                {
                    b.HasOne("AstrhoApp.API.Models.Agendum", "Agenda")
                        .WithMany("ServicioAgenda")
                        .HasForeignKey("AgendaId")
                        .IsRequired()
                        .HasConstraintName("FK__ServicioA__agend__09A971A2");

                    b.HasOne("AstrhoApp.API.Models.Servicio", "Servicio")
                        .WithMany("ServicioAgenda")
                        .HasForeignKey("ServicioId")
                        .IsRequired()
                        .HasConstraintName("FK__ServicioA__servi__08B54D69");

                    b.Navigation("Agenda");

                    b.Navigation("Servicio");
                });

            modelBuilder.Entity("AstrhoApp.API.Models.Usuario", b =>
                {
                    b.HasOne("AstrhoApp.API.Models.Rol", "Rol")
                        .WithMany("Usuarios")
                        .HasForeignKey("RolId")
                        .IsRequired()
                        .HasConstraintName("FK__Usuario__rol_id__440B1D61");

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("AstrhoApp.API.Models.Ventum", b =>
                {
                    b.HasOne("AstrhoApp.API.Models.Cliente", "DocumentoClienteNavigation")
                        .WithMany("Venta")
                        .HasForeignKey("DocumentoCliente")
                        .IsRequired()
                        .HasConstraintName("FK_Venta_Documento_Cliente");

                    b.HasOne("AstrhoApp.API.Models.MetodoPago", "Metodopago")
                        .WithMany("Venta")
                        .HasForeignKey("MetodopagoId")
                        .IsRequired()
                        .HasConstraintName("FK_Venta_metodopago_id");

                    b.Navigation("DocumentoClienteNavigation");

                    b.Navigation("Metodopago");
                });

            modelBuilder.Entity("AstrhoApp.API.Models.Agendum", b =>
                {
                    b.Navigation("ServicioAgenda");
                });

            modelBuilder.Entity("AstrhoApp.API.Models.Categorium", b =>
                {
                    b.Navigation("Insumos");
                });

            modelBuilder.Entity("AstrhoApp.API.Models.Cliente", b =>
                {
                    b.Navigation("Agenda");

                    b.Navigation("Venta");
                });

            modelBuilder.Entity("AstrhoApp.API.Models.Compra", b =>
                {
                    b.Navigation("DetalleCompras");
                });

            modelBuilder.Entity("AstrhoApp.API.Models.Empleado", b =>
                {
                    b.Navigation("Agenda");

                    b.Navigation("Entregainsumos");

                    b.Navigation("HorarioEmpleados");
                });

            modelBuilder.Entity("AstrhoApp.API.Models.Entregainsumo", b =>
                {
                    b.Navigation("DetalleEntregas");
                });

            modelBuilder.Entity("AstrhoApp.API.Models.Estado", b =>
                {
                    b.Navigation("Agenda");
                });

            modelBuilder.Entity("AstrhoApp.API.Models.Horario", b =>
                {
                    b.Navigation("HorarioEmpleados");
                });

            modelBuilder.Entity("AstrhoApp.API.Models.Insumo", b =>
                {
                    b.Navigation("DetalleCompras");

                    b.Navigation("DetalleEntregas");
                });

            modelBuilder.Entity("AstrhoApp.API.Models.MetodoPago", b =>
                {
                    b.Navigation("Agenda");

                    b.Navigation("Venta");
                });

            modelBuilder.Entity("AstrhoApp.API.Models.Permiso", b =>
                {
                    b.Navigation("RolPermisos");
                });

            modelBuilder.Entity("AstrhoApp.API.Models.Proveedor", b =>
                {
                    b.Navigation("Compras");
                });

            modelBuilder.Entity("AstrhoApp.API.Models.Rol", b =>
                {
                    b.Navigation("RolPermisos");

                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("AstrhoApp.API.Models.Servicio", b =>
                {
                    b.Navigation("DetalleVentas");

                    b.Navigation("ServicioAgenda");
                });

            modelBuilder.Entity("AstrhoApp.API.Models.Usuario", b =>
                {
                    b.Navigation("Clientes");

                    b.Navigation("Empleados");

                    b.Navigation("Entregainsumos");
                });

            modelBuilder.Entity("AstrhoApp.API.Models.Ventum", b =>
                {
                    b.Navigation("Agenda");

                    b.Navigation("DetalleVentas");
                });
#pragma warning restore 612, 618
        }
    }
}
